# Generated by Django 5.2 on 2025-04-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=12)),
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('availability', models.BooleanField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
